version: 2
jobs:
  build:
    steps:
      - run:
          name: Install Kind
          command: |
          curl -Lo ./kind-linux-amd64 https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
          chmod +x ./kind-linux-amd64
          mv ./kind-linux-amd64 /$PATH/kind
