version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Install Kind
          command: |
            curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
      - run:
          name: Start Kind
          command: |
            kind create cluster
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            export KUBECONFIG=$(kind get kubeconfig-path)
            kubectl version
      - run: go version   
  go:
    machine: true
    steps:
      - run: 
          name: Update golang 
          command: |
            curl -LO https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go/
            sudo tar -C /usr/local -xzf go1.12.7.linux-amd64.tar.gz
            sudo echo "export PATH=$PATH:/usr/local/go/bin" >> $HOME/.profile
            go version
      - run:
          command: go get github.com/onsi/ginkgo/ginkgo

  # kind:
  #   docker:
  #     - image: circleci/golang:1.12
  #       environment:
  #         - GO111MODULE=on    
  #   steps:      
  #     - setup_remote_docker
  #     - run:
  #         name: Install Kind
  #         command: |
  #           curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
  #           chmod +x ./kind
  #           sudo mv ./kind /usr/local/bin/kind      
  #     - run:
  #         name: Install kubectl
  #         command: |
  #           curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  #           chmod +x ./kubectl
  #           sudo mv ./kubectl /usr/local/bin/kubectl
  #     - run: kind create cluster
  #     - run: 
  #         name: test kubectl
  #         command: |
  #           export KUBECONFIG=$(kind get kubeconfig-path)
            
  #           cat $KUBECONFIG
  test:
    docker:
      - image: circleci/golang:1.12            
    steps:            
      - run: echo "test"
workflows:
  version: 2
  "test, build, and relase":
    jobs:
      - go:
          filters:
            tags:
              only: /.*/
      # - kind:
      #     filters:
      #       tags:
      #         only: /.*/              
      # - test:
      #     filters:
      #       tags:
      #         only: /.*/      